# Generated by Django 4.2.6 on 2023-10-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiberworks_app', '0002_product_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
