# Generated by Django 4.2.6 on 2023-10-22 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiberworks_app', '0005_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
