# Generated by Django 4.2.6 on 2023-10-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiberworks_app', '0007_customer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('hats', 'hats'), ('shawls', 'shawls'), ('blankets', 'blankets'), ('scarves', 'scarves'), ('other', 'other')], default='hats', max_length=20),
        ),
    ]
