# Generated by Django 4.2.6 on 2023-10-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiberworks_app', '0010_order_date_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='tags',
            field=models.ManyToManyField(to='fiberworks_app.tag'),
        ),
    ]
