# Generated by Django 4.2.6 on 2023-11-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiberworks_app', '0014_remove_product_product_image_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homescreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='fiberworks_app.tag'),
        ),
    ]
