# Generated by Django 4.2.6 on 2023-11-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiberworks_app', '0015_homescreen_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homescreen',
            name='intro',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
