# Generated by Django 4.2.6 on 2023-11-02 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiberworks_app', '0017_homescreen_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homescreen',
            old_name='intro',
            new_name='paragraph',
        ),
    ]
